### ISSUE TITLE
Support gzipped contracts

### ISSUE THREAD

**Issue by hoomp3** [AbstractSDK/cw-orchestrator#161]
Cosmos chains support the uploading of gzip'd wasm code (https://github.com/CosmWasm/wasmd/issues/18), which helps get around the max gas allowed per block when uploading bigger smart contracts.

Currently, the `WasmPath` type returned by implementing the `Uploadable` trait requires that the file has an extension of `.wasm`. 

There should be a way to support `.wasm.gz` extensions as well and/or compress the wasm with gzip before uploading it.

**Comment by Buckram123** [comment]
I would not prefer to zip it manually, but I like the idea of compressing the wasm with gzip before uploading it. But was not able to produce supported format by flate2/libflate, unless I'm doing something wrong, take a look: https://github.com/AbstractSDK/cw-orchestrator/blob/c95337fa5bf0c5e78bd8d49d248846036564bc2a/cw-orch/src/daemon/sync/core.rs#L102-L109

The error: ` Error calling the VM: Error during static Wasm validation:`
