### ISSUE TITLE
Allow updating of GAS_BUFFER

### ISSUE THREAD

**Issue by adairrr** [AbstractSDK/cw-orchestrator#167]
Right now, `GAS_BUFFER` is hardcoded: https://github.com/AbstractSDK/cw-orchestrator/blob/6abd736c2d3676bd3af5f7adbc62299fc352b69a/cw-orch/src/daemon/tx_builder.rs#L12 and we should allow for it to be set to a custom value, perhaps in the `ChainInfo`.

**Comment by Kayanski** [comment]
Solved by : https://github.com/AbstractSDK/cw-orchestrator/pull/210
