### ISSUE TITLE
Update syn to 2.0 + Better attributes management

### ISSUE THREAD

**Issue by Kayanski** [AbstractSDK/cw-orchestrator#219]
Syn 2.0 provides better management for proc_macro parsing, and has a better way of managing attributes on them. 
This would clarify the code as well as have it up to date with rust standards

**Comment by Kayanski** [comment]
Closed by https://github.com/AbstractSDK/cw-orchestrator/pull/488

**Comment by CyberHoward** [comment]
whoeps, my bad
