### ISSUE TITLE
Add support for test-tube as an execution environment.

### ISSUE THREAD

**Issue by CyberHoward** [AbstractSDK/cw-orchestrator#3]
The [osmosis-test-tube](https://github.com/osmosis-labs/test-tube) is a FFI-based CosmWasm execution environment that can be used to test contracts that use app-chain specific logic without requiring a mock. 

By adding support for this execution environment users get easy access to the Osmosis specific logic with possibly more chains supporting it in the future.

**Comment by Kayanski** [comment]
Closed by https://github.com/AbstractSDK/cw-orchestrator/pull/150
