### ISSUE TITLE
State file content non-deterministic

### ISSUE THREAD

**Issue by CyberHoward** [AbstractSDK/cw-orchestrator#327]
The state file's content is not sorted. This causes some PRs to contain changes to the state without there actually being a change in the content. 

Example: https://github.com/AbstractSDK/abstract/pull/226/files/4c44670162905c46265f1db6235e1281fae716c3#diff-4a31530d26798a73bdb7ac7e5f704129fb4320dc063a5125fcca878f2af0b94c

This makes it hard to review these kinds of PRs.

**Comment by Kayanski** [comment]
This is due to a manual state change in Abstract.
Cw-orch always sorts the state when writing to the state file.
