### ISSUE TITLE
chore: use upstream cw20

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AbstractSDK/cw-orchestrator#366]
https://github.com/AbstractSDK/cw-orchestrator/blob/859ba48d313f9c80536940fd0a9766999a90dbd0/Cargo.toml#L17

**Comment by Kayanski** [comment]
Hello ! This will be reviewed once cw-orch is stabilized.

**Comment by Kayanski** [comment]
Hello ! https://github.com/AbstractSDK/cw-orchestrator/pull/500 fixes this, we have move the cw-plus interfaces inside the [repo](https://github.com/AbstractSDK/cw-orchestrator/tree/776a34afd27f087104d149987ad06645a2a43651/packages/integrations/cw-plus)

**Comment by Kayanski** [comment]
Fixed by #500
