### ISSUE TITLE
feat: feature gate some cw-orch dependencies

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AbstractSDK/cw-orchestrator#367]
https://github.com/AbstractSDK/cw-orchestrator/blob/859ba48d313f9c80536940fd0a9766999a90dbd0/Cargo.toml#L22C2-L22C19

- feature gate osmosis test tube (allow to start small just from in memory tests)
- consider feature gate ibc chain registry too (so can start in mem -> local custom setup -> remote) as deps

**Comment by Kayanski** [comment]
`cw-orch-networks` could be gated behind the `daemon` feature because it's mostly used with `daemons` and not really on its own

**Comment by Kayanski** [comment]
Renaming the issue to remove the osmosis test tube mention. Osmosis Test Tube is already gated behing `osmosis-test-tube` feature

**Comment by dzmitry-lahoda** [comment]
oh, sorry, looked into wrong Cargo.toml. thank you.
