### ISSUE TITLE
Does not support 12-word mnemonics

### ISSUE THREAD

**Issue by adairrr** [AbstractSDK/cw-orchestrator#48]
Although the logic appears that it supports 12-word keys, in practice it does not.

Likely an issue with this method:
https://github.com/Abstract-OS/BOOT/blob/69c5e1f29545b11f5db91069c2c56760f34cf054/boot-core/src/keys/private.rs#L52-L65

**Comment by CyberHoward** [comment]
Will just throw an error if the mnemonic is not 24 words for now.
