### ISSUE TITLE
Move environments to their own crate

### ISSUE THREAD

**Issue by CyberHoward** [AbstractSDK/cw-orchestrator#70]
Because of the continual development of BOOT, new version are often released. Because trait implementations between versions are not considered compatible any bump to the `boot-core` crate causes issues for compatibility between users.  

To solve this we can move the BOOT environments to a separate crate which allows us to develop and add new environments without requiring new `boot-core` releases. This should help us keep API stability for the key BOOT features without strangling our ability to add/update the environments.

**Comment by Kayanski** [comment]
Closed by https://github.com/AbstractSDK/cw-orchestrator/pull/152
